services:
  dev:
    build:
      context: ./docker/cicd
    volumes:
      - type: bind
        source: .
        target: /mnt/gh_test
    working_dir: /mnt/gh_test
    stdin_open: true
    tty: true
    command: /bin/bash

  build:
    image: rust:latest
    volumes:
      - type: bind
        source: .
        target: /mnt/gh_test
    working_dir: /mnt/gh_test
    command: cargo build --release

  test:
    image: rust:latest
    volumes:
      - type: bind
        source: .
        target: /mnt/gh_test
    working_dir: /mnt/gh_test
    command: cargo test

  release:
    build:
      context: ./docker/cicd
    volumes:
      - type: bind
        source: .
        target: /mnt/gh_test
    working_dir: /mnt/gh_test
    entrypoint: bash /mnt/gh_test/docker/cicd/release.sh
